syslog = '^(\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+([\w\d\.-]+)\s+([\w\d\.-\/]+)(\[(\d+)?\])?:\s+(.+)$'
commonLogFormat = '^(\S+)\s+(\S+)\s+(\S+)\s+\[([^]]+)\]\s+"([^"]+)"\s+(\d+)\s+(\d+|-)$'
apacheErrorLog = '^\[(\w{3}\s+\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\s+\d{4})\]\s+\[(\w+)\]\s+\[client\s+([\d\.]+)(:\d+)?\]\s+(.*)$'
