package components

import (
	"github.com/claude42/infiltrator/util"
)

// Generated by InputImpl, FilterInput

type EventText struct {
	util.EventImpl

	text string
}

func NewEventText(text string) *EventText {
	ev := &EventText{text: text}
	ev.EventImpl.SetWhen()
	return ev
}

func (ev *EventText) Text() string {
	return ev.text
}

func (ev *EventText) SetText(text string) {
	ev.text = text
}
